
#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE USER $PG_CUSTOM_USER WITH ENCRYPTED PASSWORD '$PG_CUSTOM_PASS';
	CREATE DATABASE $PG_CUSTOM_DB;
	-- GRANT ALL PRIVILEGES ON DATABASE docker TO docker;
EOSQL
